name: Deploy Application

on:
  push:
    branches:
      - main
      - "feature-*"

jobs:
  build_and_push_docker:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

  deploy_staging:
    needs: build_and_push_docker
    runs-on: self-hosted
    steps:
      - name: Pull and run Docker container for staging
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
          docker stop staging || true
          docker rm staging || true
          docker run -d --name staging \
            -e BRANCH=${{ github.ref_name }} \
            -p 8080:80 \
            ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

  deploy_prod:
    needs: build_and_push_docker
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Pull and run Docker container for production
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
          docker stop production || true
          docker rm production || true
          docker run -d --name production \
            -p 80:80 \
            ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

  revert:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Revert to Previous Version
        run: |
          docker stop production || true
          docker rm production || true
          docker run -d --name production \
            -p 80:80 \
            ${{ secrets.DOCKER_USERNAME }}/my-app:previous-version
